### ISSUE TITLE
[BUG] Server Crash

### ISSUE THREAD

**Issue by Mattabase** [DaFuqs/LootCrates#16]
**Describe the bug**
When generating new chunks the server crashes

**To Reproduce**
I was flying around a on a server, then the server crashed

**Expected behavior**
The Server not crashing

[crash-2021-09-17_12.23.31-server.txt](https://github.com/DaFuqs/LootCrates/files/7185525/crash-2021-09-17_12.23.31-server.txt)

**Comment by DaFuqs** [comment]
> The Server no crashing
Fair assumption. 😁

Sadly I could not reproduce your crash in on my personal server instance. In 20 minutes I flew in different directions, teleported and so on, but could not get a crash like you. Was the crash right when you started exploring, or at some seemingly random time?

Since you have quite a lot of mods that mix into the part of the code please try removing mods. When I know what mod causes you issue I can fix it preceisely. Otherwise I may add some form of general failsafe, but that might result in some chests just not replacing.

**Comment by Mattabase** [comment]
I am not surprised , I also could not reproduce it after flying in one direction on a server for many hours. Guess it is a pretty extreme edge case.

Also, this is my modpack after I have ripped out half of the mods. Did that the other day when I sent it to you, more reasonable to test things.  haha

In my mind, general failsafe that logs when and where it happens may help track down who is at fault as well as let me know it has happened somewhere and I can go replace the chest by hand

**Comment by DaFuqs** [comment]
Oh yeah! It is that pack, now that you mention it!

I have added general error handling in 1.4.0. If chest replacement fails for whatever case, you will get a message in the server console like:
[LootCrates] Error while replacing a chest in the world <<world>> at <<position>> with loot table <<loottable>>

If you have another problem or a suspect, what may cause it, always feel free to open another issue. 😊
