### ISSUE TITLE
[Feature] REI Loot Handler

### ISSUE THREAD

**Issue by Mattabase** [DaFuqs/LootCrates#18]
Would be really nice to see what items are contained in lootables, and if for example lootbags were set to drop from mobs it would be great to see what could come out of those lootbags. 

Like if I have bags that drop from creepers only, would be nice for the player to hit R or whatever key they have set in REI and see where it drops, and if they U or bound key they see what loot is in the bags lootable?

**Comment by DaFuqs** [comment]
Mob drops are handled by https://github.com/theorbtwo/RoughlyEnoughResources as soon as that updates.

To specify what is contained in loot tables (perfectly would be % values) is a rather difficult task, since loot tables can contain really long dependency chains (like the loot table for leaves). This one I cannot promise, but I will leave it open for the time being, in case I have an idea. 😅
