### ISSUE TITLE
[1.16.5] Duplicating items in chests when multiple players open

### ISSUE THREAD

**Issue by spoorn** [DaFuqs/LootCrates#29]
**Describe the bug**
I'm on the latest 1.16.5 version oft he mod.  It seems the loot in each chest isn't instanced per player, but rather it duplicates all the contents when each player opens the chest.  

**To Reproduce**
Have multiple people open the same modular loot chest

**Expected behavior**
The loot should be instanced per player

**Comment by DaFuqs** [comment]
This is very much intended, sorry. The alternative would be that the chests could not be used as storage in shared bases and not interacted with via hoppers or other means of automation.
Especially with the shulker crates the automation aspect is a big thing on the servers I know, at least. Since vanilla Shulker Boxes are very hard to farm.
